import "server-only";

import * as XLSX from "xlsx-js-style";

import { cleanExcelValue } from "@/lib/export/excel-sanitize";
import {
  EXCEL_MIME_TYPE,
  EXCEL_STYLES,
  formatExcelDisplayDate,
  type CellStyle,
} from "@/lib/export/excel-style";
import type {
  NoteMonitorIndividualExportRecord,
  NoteMonitorReportFilters,
  NoteMonitorReportRow,
} from "@/lib/server/note-monitor-reports";
import { formatNoteMonitorFiltersForDisplay } from "@/lib/server/note-monitor-reports";

const EMPTY = "—";

const REPORT_HEADERS = [
  "Note Year",
  "Note Number",
  "Full Note Reference",
  "Note Type",
  "Note Preparation Date",
  "Details",
  "Date Returned from Secretary",
  "Date Sent to Executive Council",
  "Date Received from Executive Council",
  "Due Date",
  "Note Status",
  "Linked Contract",
  "Created By",
  "Created Date",
  "Last Updated By",
  "Last Updated Date",
] as const;

const DETAILS_COLUMN_WIDTH = 75;

const REPORT_COLUMN_WIDTHS: number[] = [
  10, 12, 22, 14, 18, DETAILS_COLUMN_WIDTH, 22, 24, 28, 14, 14, 28, 18, 20, 18, 20,
];

const DETAILS_COLUMN_INDEX = 5;

type PrimitiveCell = string | number;

function cell(value: unknown, emptyDisplay = EMPTY): PrimitiveCell {
  return cleanExcelValue(value, { emptyDisplay });
}

function cellDate(value: string | null | undefined): PrimitiveCell {
  const formatted = formatExcelDisplayDate(value);
  return formatted ? cell(formatted) : EMPTY;
}

function filtersSummary(filters: NoteMonitorReportFilters): string {
  const entries = Object.entries(formatNoteMonitorFiltersForDisplay(filters));
  if (entries.length === 0) return "None";
  return entries.map(([key, value]) => `${key}: ${value}`).join(" | ");
}

function setStyledCell(ws: XLSX.WorkSheet, row: number, col: number, style: CellStyle): void {
  const ref = XLSX.utils.encode_cell({ r: row, c: col });
  const existing = ws[ref];
  if (!existing) return;
  ws[ref] = { ...existing, s: style };
}

function applyRowStyle(
  ws: XLSX.WorkSheet,
  row: number,
  colCount: number,
  style: CellStyle,
): void {
  for (let col = 0; col < colCount; col += 1) {
    setStyledCell(ws, row, col, style);
  }
}

function applyBodyStyle(
  ws: XLSX.WorkSheet,
  row: number,
  colCount: number,
  wrapCols: Set<number>,
): void {
  for (let col = 0; col < colCount; col += 1) {
    setStyledCell(
      ws,
      row,
      col,
      wrapCols.has(col) ? EXCEL_STYLES.tableBodyWrap : EXCEL_STYLES.tableBody,
    );
  }
}

function applyMetaRows(ws: XLSX.WorkSheet, startRow: number, endRow: number): void {
  for (let row = startRow; row <= endRow; row += 1) {
    setStyledCell(ws, row, 0, EXCEL_STYLES.metaLabel);
    setStyledCell(ws, row, 1, EXCEL_STYLES.metaValue);
  }
}

function applyFieldRows(ws: XLSX.WorkSheet, startRow: number, endRow: number, wrapRows: Set<number>): void {
  for (let row = startRow; row <= endRow; row += 1) {
    setStyledCell(ws, row, 0, EXCEL_STYLES.fieldLabel);
    setStyledCell(
      ws,
      row,
      1,
      wrapRows.has(row) ? EXCEL_STYLES.tableBodyWrap : EXCEL_STYLES.fieldValue,
    );
  }
}

function finalizeSheet(ws: XLSX.WorkSheet, colWidths: number[]): void {
  ws["!cols"] = colWidths.map((wch) => ({ wch }));
  ws["!margins"] = {
    left: 0.5,
    right: 0.5,
    top: 0.75,
    bottom: 0.75,
    header: 0.3,
    footer: 0.3,
  };
}

function sheetFromAoa(aoa: PrimitiveCell[][]): XLSX.WorkSheet {
  return XLSX.utils.aoa_to_sheet(aoa);
}

function reportDataRowValues(row: NoteMonitorReportRow): PrimitiveCell[] {
  return [
    cell(row.noteYear),
    cell(row.noteNumber),
    cell(row.displayReference),
    cell(row.noteType),
    cellDate(row.notePreparationDate),
    cell(row.details),
    cellDate(row.dateReturnedFromSecretary),
    cellDate(row.dateSentToExecutiveCouncil),
    cellDate(row.dateReceivedFromExecutiveCouncil),
    cellDate(row.dueDate),
    cell(row.status),
    cell(row.linkedContracts),
    cell(row.createdBy),
    cell(row.createdDate),
    cell(row.lastUpdatedBy),
    cell(row.lastUpdatedDate),
  ];
}

function buildNoteMonitorReportSheet(input: {
  rows: NoteMonitorReportRow[];
  filters: NoteMonitorReportFilters;
  generatedAt: string;
  generatedBy: string | null;
}): XLSX.WorkSheet {
  const aoa: PrimitiveCell[][] = [
    [cell("Note Monitor Report")],
    ["Generated At", cell(input.generatedAt)],
    ["Generated By", cell(input.generatedBy || EMPTY)],
    ["Filters Used", cell(filtersSummary(input.filters))],
    ["Total Records Exported", cell(input.rows.length)],
    [],
    [...REPORT_HEADERS],
  ];

  const headerRow = aoa.length - 1;
  const dataStartRow = headerRow + 1;

  if (input.rows.length > 0) {
    for (const row of input.rows) {
      aoa.push(reportDataRowValues(row));
    }
  } else {
    aoa.push(["No records found for the selected filters."]);
  }

  const ws = sheetFromAoa(aoa);
  const colCount = REPORT_HEADERS.length;

  setStyledCell(ws, 0, 0, EXCEL_STYLES.reportTitle);
  applyMetaRows(ws, 1, 4);
  applyRowStyle(ws, headerRow, colCount, EXCEL_STYLES.tableHeader);

  const wrapCols = new Set([DETAILS_COLUMN_INDEX]);
  for (let row = dataStartRow; row < aoa.length; row += 1) {
    if (input.rows.length === 0) {
      setStyledCell(ws, row, 0, EXCEL_STYLES.notice);
    } else {
      applyBodyStyle(ws, row, colCount, wrapCols);
    }
  }

  finalizeSheet(ws, REPORT_COLUMN_WIDTHS);
  ws["!name"] = "Note Monitor Report";
  return ws;
}

function buildNoteDetailsSheet(input: {
  record: NoteMonitorIndividualExportRecord;
  generatedAt: string;
  generatedBy: string;
}): XLSX.WorkSheet {
  const fields: Array<[string, PrimitiveCell, boolean]> = [
    ["Full Note Reference", cell(input.record.displayReference), false],
    ["Note Type", cell(input.record.noteType), false],
    ["Note Year", cell(input.record.noteYear), false],
    ["Note Number", cell(input.record.noteNumber), false],
    ["Note Preparation Date", cellDate(input.record.notePreparationDate), false],
    ["Details", cell(input.record.details), true],
    ["Date Returned from Secretary", cellDate(input.record.dateReturnedFromSecretary), false],
    ["Date Sent to Executive Council", cellDate(input.record.dateSentToExecutiveCouncil), false],
    [
      "Date Received from Executive Council",
      cellDate(input.record.dateReceivedFromExecutiveCouncil),
      false,
    ],
    ["Due Date", cellDate(input.record.dueDate), false],
    ["Note Status", cell(input.record.status), false],
    ["Created By", cell(input.record.createdBy), false],
    ["Created Date", cell(input.record.createdDate), false],
    ["Last Updated By", cell(input.record.lastUpdatedBy), false],
    ["Last Updated Date", cell(input.record.lastUpdatedDate), false],
  ];

  const aoa: PrimitiveCell[][] = [
    [cell(`Note Monitor Record: ${input.record.displayReference}`)],
    ["Generated At", cell(input.generatedAt)],
    ["Generated By", cell(input.generatedBy || EMPTY)],
    [],
    ...fields.map(([label, value]) => [label, value]),
  ];

  const ws = sheetFromAoa(aoa);
  const fieldStartRow = 4;
  const fieldEndRow = fieldStartRow + fields.length - 1;
  const wrapRows = new Set(
    fields.map(([, , wrap], index) => (wrap ? fieldStartRow + index : -1)).filter((row) => row >= 0),
  );

  setStyledCell(ws, 0, 0, EXCEL_STYLES.reportTitle);
  applyMetaRows(ws, 1, 2);
  applyFieldRows(ws, fieldStartRow, fieldEndRow, wrapRows);

  finalizeSheet(ws, [34, DETAILS_COLUMN_WIDTH]);
  ws["!name"] = "Note Details";
  return ws;
}

function buildLinkedContractsSheet(record: NoteMonitorIndividualExportRecord): XLSX.WorkSheet {
  const headers = ["Employee", "File Number", "Contract Number", "Role", "Status"];
  const widths = [28, 14, 18, 22, 14];
  const aoa: PrimitiveCell[][] = [headers];

  if (record.linkedContracts.length > 0) {
    for (const contract of record.linkedContracts) {
      aoa.push([
        cell(contract.employeeName),
        cell(contract.fileNumber),
        cell(contract.contractNumber),
        cell(contract.role),
        cell(contract.status),
      ]);
    }
  } else {
    aoa.push(["No contract has been linked to this note."]);
  }

  const ws = sheetFromAoa(aoa);
  const colCount = headers.length;
  applyRowStyle(ws, 0, colCount, EXCEL_STYLES.tableHeader);

  for (let row = 1; row < aoa.length; row += 1) {
    if (record.linkedContracts.length === 0) {
      setStyledCell(ws, row, 0, EXCEL_STYLES.notice);
    } else {
      applyBodyStyle(ws, row, colCount, new Set());
    }
  }

  finalizeSheet(ws, widths);
  ws["!name"] = "Linked Contracts";
  return ws;
}

function buildEditHistorySheet(record: NoteMonitorIndividualExportRecord): XLSX.WorkSheet {
  const headers = ["Date/Time", "Edited By", "Action", "Field", "Previous Value", "New Value"];
  const widths = [22, 20, 14, 18, 30, 30];
  const wrapCols = new Set([4, 5]);
  const aoa: PrimitiveCell[][] = [headers];

  if (record.history.length > 0) {
    for (const entry of record.history) {
      aoa.push([
        cell(entry.editedAt),
        cell(entry.editedBy),
        cell(entry.action),
        cell(entry.field),
        cell(entry.previousValue, ""),
        cell(entry.newValue, ""),
      ]);
    }
  } else {
    aoa.push(["No edit history recorded yet."]);
  }

  const ws = sheetFromAoa(aoa);
  const colCount = headers.length;
  applyRowStyle(ws, 0, colCount, EXCEL_STYLES.tableHeader);

  for (let row = 1; row < aoa.length; row += 1) {
    if (record.history.length === 0) {
      setStyledCell(ws, row, 0, EXCEL_STYLES.notice);
    } else {
      applyBodyStyle(ws, row, colCount, wrapCols);
    }
  }

  finalizeSheet(ws, widths);
  ws["!name"] = "Edit History";
  return ws;
}

export function buildNoteMonitorReportWorkbook(input: {
  rows: NoteMonitorReportRow[];
  filters: NoteMonitorReportFilters;
  generatedAt: string;
  generatedBy: string | null;
}): XLSX.WorkBook {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, buildNoteMonitorReportSheet(input), "Note Monitor Report");
  return workbook;
}

export function buildNoteMonitorIndividualWorkbook(input: {
  record: NoteMonitorIndividualExportRecord;
  generatedAt: string;
  generatedBy: string;
}): XLSX.WorkBook {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, buildNoteDetailsSheet(input), "Note Details");
  XLSX.utils.book_append_sheet(workbook, buildLinkedContractsSheet(input.record), "Linked Contracts");
  XLSX.utils.book_append_sheet(workbook, buildEditHistorySheet(input.record), "Edit History");
  return workbook;
}

function isValidXlsxBuffer(buffer: Buffer): boolean {
  return buffer.length >= 4 && buffer[0] === 0x50 && buffer[1] === 0x4b;
}

export function isValidXlsxBase64(contentBase64: string): boolean {
  const trimmed = contentBase64.trim();
  if (!trimmed) return false;
  try {
    return isValidXlsxBuffer(Buffer.from(trimmed, "base64"));
  } catch {
    return false;
  }
}

export function workbookToBase64(workbook: XLSX.WorkBook): string {
  const buffer = XLSX.write(workbook, { type: "buffer", bookType: "xlsx" }) as Buffer;
  if (!isValidXlsxBuffer(buffer)) {
    throw new Error("Generated workbook is not a valid XLSX zip archive");
  }
  return buffer.toString("base64");
}

export const NOTE_MONITOR_EXCEL_MIME = EXCEL_MIME_TYPE;

export {
  buildNoteMonitorExportAuditDescription as buildNoteMonitorReportAuditLabel,
  buildNoteMonitorIndividualFileName as buildNoteMonitorNoteFileName,
  buildNoteMonitorReportFileName,
  normalizeNoteMonitorReportFilters,
  validateNoteMonitorReportFilters,
} from "@/lib/server/note-monitor-reports";

export function buildNoteMonitorNoteWorkbook(input: {
  record: NoteMonitorIndividualExportRecord;
  generatedAt: string;
  generatedBy: string | null;
}): XLSX.WorkBook {
  return buildNoteMonitorIndividualWorkbook({
    record: input.record,
    generatedAt: input.generatedAt,
    generatedBy: input.generatedBy ?? "",
  });
}
